*There are mainly two types of data*  
*-Numerical data*  
*-Categorical data*  

*categorical data can be further divided into:*  
*- Nominal data*   
*- categorical data*  

**Encoding is the process of converting categorical data into numerical as most of the ml algos expect data in numerical forms**

*for ordinal data ---> Ordinal encoding/(label encoding)*  
*for nominal data ---> one hot encoding*  

Ordinal encoder vs label encoder

*for input variable we use ordinal encoder*  
*for target variable (output) we use label encoder*

In [1]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
#loading datset
df = pd.read_csv('customer.csv')
df.head(10)

,age,gender,review,education,purchased
0,30,Female,Average,School,No
1,68,Female,Poor,UG,No
2,70,Female,Good,PG,No
3,72,Female,Good,PG,No
4,16,Female,Average,UG,No
5,31,Female,Average,School,Yes
6,18,Male,Good,School,No
7,60,Female,Poor,School,Yes
8,65,Female,Average,UG,No
9,74,Male,Good,UG,Yes


*there are 4 input variable*
- *age--->numerical(discrete)*
- *gender---->nominal*
- *review----->ordinal*
- *education---->ordinal*

*there is one target/output variable*
- *purchased ----> nominal*

## Ordinal Encoding

*in this example we will only do ordinal encoding so selecting only ordinal columns*

In [8]:
df = df.iloc[:,2:]
df.head()

,review,education,purchased
0,Average,School,No
1,Poor,UG,No
2,Good,PG,No
3,Good,PG,No
4,Average,UG,No


In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [9]:
from sklearn.preprocessing import OrdinalEncoder

In [22]:
X_train

,review,education
47,Good,PG
18,Good,School
44,Average,UG
19,Poor,PG
20,Average,School
17,Poor,UG
5,Average,School
4,Average,UG
3,Good,PG
29,Average,UG


In [23]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

***we have to define categories otherwise it may be in random order.***

In [24]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [25]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [15]:
X_train

array([[2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [1., 1.],
       [0., 0.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [0., 2.],
       [1., 0.],
       [2., 2.],
       [1., 0.],
       [1., 0.],
       [2., 0.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [0., 1.],
       [2., 2.],
       [2., 2.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [1., 2.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [1., 2.],
       [2., 1.],
       [0., 0.],
       [1., 1.],
       [1., 2.],
       [1., 1.]])

In [26]:
X_train = pd.DataFrame(X_train,columns=['review','education'])
X_train

,review,education
0,2.0,2.0
1,2.0,0.0
2,1.0,1.0
3,0.0,2.0
4,1.0,0.0
5,0.0,1.0
6,1.0,0.0
7,1.0,1.0
8,2.0,2.0
9,1.0,1.0


In [27]:
X_test = pd.DataFrame(X_test,columns=['review','education'])
X_test

,review,education
0,1.0,2.0
1,2.0,1.0
2,2.0,0.0
3,2.0,2.0
4,2.0,0.0
5,2.0,0.0
6,0.0,0.0
7,1.0,2.0
8,1.0,0.0
9,0.0,0.0


In [28]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [29]:
le.fit(y_train)

LabelEncoder()

In [30]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [31]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [32]:
y_train

array([1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0])

## One Hot Encoding

*Why can't we encode nominal data as we do ordinal data?*

*Because our machine learning models may interpret nominal data as having an order. For instance, if there are three colors—let's say Red, Green, and Blue—and we encode them as Red = 0, Green = 1, and Blue = 2, the model might assume that Blue is greater or more important than Red and Green, which is not the case.*

![one hot encoding](ohe.png)

***Dummy Variable Trap***

- *After doing one hot encoding, we have to remove one of the dummy columns to remove the problem of multicolinearity*
- *to make all columns independent*

In [4]:
data = pd.read_csv('cars.csv')
data

,brand,km_driven,fuel,owner,selling_price
0,Maruti,145500,Diesel,First Owner,450000
1,Skoda,120000,Diesel,Second Owner,370000
2,Honda,140000,Petrol,Third Owner,158000
3,Hyundai,127000,Diesel,First Owner,225000
4,Maruti,120000,Petrol,First Owner,130000
...,...,...,...,...,...
8123,Hyundai,110000,Petrol,First Owner,320000
8124,Hyundai,119000,Diesel,Fourth & Above Owner,135000
8125,Maruti,120000,Diesel,First Owner,382000
8126,Tata,25000,Diesel,First Owner,290000


In [6]:
type(data)

pandas.core.frame.DataFrame

In [7]:
data.brand.value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [8]:
data.fuel.value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [9]:
data.owner.value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

*we can see that owner and fuel has less nominal value where brand has many, so if we apply OHE on brand then many new cols about 40 as different brands are created which makes very high no of columns so processing becomes hard and slow in such case we have to group uncommon i.e less frequent columns into single to reduce dimensonality*

## **1. One Hot Encoding using Pandas**

In [13]:
pd.get_dummies(data,columns=['fuel','owner'],dtype=int) #not doing for brand now as it contains many values

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0


## **2. K-1 OneHotEncoding**

*still there is problem of multicolinearity*

In [14]:
pd.get_dummies(data,columns=['fuel','owner'],dtype=int,drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0


## **3. OneHotEncoding using Sklearn**

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(data.iloc[:,0:4],data.iloc[:,-1],test_size=0.2,random_state=2)
X_train.head()

,brand,km_driven,fuel,owner
5571,Hyundai,35000,Diesel,First Owner
2038,Jeep,60000,Diesel,First Owner
2957,Hyundai,25000,Petrol,First Owner
7618,Mahindra,130000,Diesel,Second Owner
6684,Hyundai,155000,Diesel,First Owner


In [17]:
from sklearn.preprocessing import OneHotEncoder

In [25]:
ohe = OneHotEncoder(sparse_output=False,drop='first')
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])
X_train_new

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [26]:
X_test_new = ohe.fit_transform(X_test[['fuel','owner']])
X_test_new

array([[0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [30]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Hyundai', 35000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Jeep', 60000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Hyundai', 25000, 0.0, ..., 0.0, 0.0, 0.0],
       ...,
       ['Tata', 15000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 32500, 1.0, ..., 1.0, 0.0, 0.0],
       ['Isuzu', 121000, 1.0, ..., 0.0, 0.0, 0.0]], dtype=object)

In [29]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new)).shape

(6502, 9)

## **4. OneHotEncoding with Top Categories**

In [31]:
counts = data['brand'].value_counts()
counts

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [32]:
data['brand'].nunique()
threshold = 100

In [33]:
replace = counts[counts <= threshold].index
replace

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Force', 'Land', 'Isuzu', 'Kia',
       'Ambassador', 'Daewoo', 'MG', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [36]:
pd.get_dummies(data['brand'].replace(replace, 'uncommon'),dtype=int).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
1091,1,0,0,0,0,0,0,0,0,0,0,0,0
6753,0,0,0,1,0,0,0,0,0,0,0,0,0
3940,0,1,0,0,0,0,0,0,0,0,0,0,0
6668,0,0,0,0,0,0,0,0,0,1,0,0,0
5065,0,0,0,0,0,0,1,0,0,0,0,0,0
