# **Types of Gradient Descent**

*Generally, types of gradient descent can be divided in three types*
- Batch Gradient Descent
- stochastic Gradient descent
- mini batch gradient descent  

**Batch Gradient Descent** : *A type of gradient descent where the entire dataset (all rows) is used to compute the gradient and update the coefficients once per iteration.*

**Stochastic Gradient Descent** : *A type of gradient descent where one data point (a single row) is used to compute the gradient and update the coefficients. This happens once per row, so multiple updates per epoch*

**Mini Batch Gradient Descent** : *A type of gradient descent where a small batch of rows (e.g., 30 rows at a time) is used to compute the gradient and update the coefficients.*
- **Example**: *If you have 300 rows and batch size = 30, you’ll have 10 updates per epoch.*

# **Batch Gradient Descent**

**Pros**:
- ✅ Stable convergence

**Cons**:
- ❌ Can be very slow for large datasets
- ❌ Memory-intensive

### 📘 Batch Gradient Descent in Multiple Linear Regression

Suppose we are solving a **Multiple Linear Regression** problem with an **n-dimensional input vector**.

The hypothesis (prediction) function is:

$$
\hat{y} = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \cdots + \beta_n x_n
$$

Or in **vectorized form**:

$$
\hat{y} = \boldsymbol{\beta}^\top \mathbf{x}
$$

Where:
- $\boldsymbol{\beta} = [\beta_0, \beta_1, \ldots, \beta_n]^\top$ is the **(n+1)-dimensional coefficient vector**
- $\mathbf{x} = [1, x_1, x_2, \ldots, x_n]^\top$ includes the **bias term** (1 for $\beta_0$)

---

### 🎯 Goal
Minimize the **Mean Squared Error (MSE)** cost function:

$$
J(\boldsymbol{\beta}) = \frac{1}{2m} \sum_{i=1}^{m} \left( \hat{y}^{(i)} - y^{(i)} \right)^2
$$

Where:
- $m$ = number of training examples
- $\hat{y}^{(i)} = \boldsymbol{\beta}^\top \mathbf{x}^{(i)}$

---

### 🧮 Partial Derivatives of the Cost Function

To perform gradient descent, we compute the **partial derivative** of the cost function with respect to each parameter $\beta_j$:

$$
\frac{\partial J}{\partial \beta_j} = \frac{1}{m} \sum_{i=1}^{m} \left( \hat{y}^{(i)} - y^{(i)} \right) x_j^{(i)}
$$

This gives the direction in which the parameter $\beta_j$ should be adjusted to minimize the cost.

---

### 🔁 Batch Gradient Descent Algorithm

At each iteration, update each coefficient using the partial derivative:

$$
\beta_j := \beta_j - \alpha \cdot \frac{\partial J}{\partial \beta_j}
= \beta_j - \alpha \cdot \frac{1}{m} \sum_{i=1}^{m} \left( \hat{y}^{(i)} - y^{(i)} \right) x_j^{(i)}
\quad \text{for } j = 0, 1, \ldots, n
$$

Where:
- $\alpha$ = learning rate
- $x_0^{(i)} = 1$ (for the intercept $\beta_0$)

---

### ✅ Example: 3-Dimensional Input

Let’s consider:

$$
\hat{y} = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \beta_3 x_3
$$

Then the partial derivatives are:

$$
\frac{\partial J}{\partial \beta_0} = \frac{1}{m} \sum_{i=1}^{m} \left( \hat{y}^{(i)} - y^{(i)} \right)
$$

$$
\frac{\partial J}{\partial \beta_1} = \frac{1}{m} \sum_{i=1}^{m} \left( \hat{y}^{(i)} - y^{(i)} \right) x_1^{(i)}
$$

$$
\frac{\partial J}{\partial \beta_2} = \frac{1}{m} \sum_{i=1}^{m} \left( \hat{y}^{(i)} - y^{(i)} \right) x_2^{(i)}
$$

$$
\frac{\partial J}{\partial \beta_3} = \frac{1}{m} \sum_{i=1}^{m} \left( \hat{y}^{(i)} - y^{(i)} \right) x_3^{(i)}
$$

So the update rules become:

$$
\beta_0 := \beta_0 - \alpha \cdot \frac{\partial J}{\partial \beta_0}
$$

$$
\beta_1 := \beta_1 - \alpha \cdot \frac{\partial J}{\partial \beta_1}
$$

$$
\beta_2 := \beta_2 - \alpha \cdot \frac{\partial J}{\partial \beta_2}
$$

$$
\beta_3 := \beta_3 - \alpha \cdot \frac{\partial J}{\partial \beta_3}
$$

---

### 📌 Key Characteristics of Batch Gradient Descent

**Pros**:
- ✅ Stable convergence
- ✅ Accurate gradient calculation (based on full dataset)

**Cons**:
- ❌ Slow for large datasets
- ❌ Requires loading the entire dataset into memory

---

### 🔍 Summary

Batch Gradient Descent updates all coefficients **after computing the gradients from the full dataset**.  
Each update is based on the **partial derivative of the cost function with respect to each coefficient**, ensuring the model moves in the direction of steepest descent.

It is stable and accurate, but computationally expensive for large datasets.


## Code-Example

In [2]:
from sklearn.datasets import load_diabetes #loading dataset from scikit-learn
import numpy as np
from sklearn.linear_model import LinearRegression #importing LinearRegression model
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [3]:
X,y = load_diabetes(return_X_y=True)

In [4]:
X,y

(array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
   

In [5]:
X.shape

(442, 10)

In [6]:
y.shape

(442,)

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [9]:
reg = LinearRegression()
reg.fit(X_train,y_train)  #training linear regression model using scikit-learn in built class

LinearRegression()

In [10]:
reg.coef_

array([  26.9897914 , -205.86000038,  553.77572081,  316.6849536 ,
       -793.34998441,  458.32498786,  160.92247748,  214.48901695,
        778.5878875 ,    4.68820871])

*as there is 10 input feature in our data 10 coeffecient*

In [11]:
reg.intercept_

154.48361855786288

*one intercept plus 10 coefficent = 11 total*

In [12]:
y_pred = reg.predict(X_test) #inferencing on test data

In [13]:
r2_score(y_test,y_pred)

0.4900882767570658

*49% r2 score using scikit_learn implementation*

**Using own implementation form scratch**

In [14]:
class GDRegressor:
    
    def __init__(self,learning_rate=0.01,epochs=100):
        
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        
    def fit(self,X_train,y_train):
        # init your coefs
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        
        for i in range(self.epochs):
            # update all the coef and the intercept
            y_hat = np.dot(X_train,self.coef_) + self.intercept_
            #print("Shape of y_hat",y_hat.shape)
            intercept_der = -2 * np.mean(y_train - y_hat)
            self.intercept_ = self.intercept_ - (self.lr * intercept_der)
            
            coef_der = -2 * np.dot((y_train - y_hat),X_train)/X_train.shape[0]
            self.coef_ = self.coef_ - (self.lr * coef_der)
        
        print(self.intercept_,self.coef_)
    
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [15]:
gdr = GDRegressor(epochs=1000,learning_rate=0.5)

In [16]:
gdr.fit(X_train,y_train)

154.23703169468573 [  38.67229968 -169.47414133  500.92988121  295.58594348  -28.69347422
 -107.1269363  -183.42935176  134.16378498  412.44124696   71.52125116]


In [17]:
y_pred = gdr.predict(X_test)

In [18]:
r2_score(y_test,y_pred)

0.49442170068074454